# Generated by Django 5.0.6 on 2024-05-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warsztaty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='availability',
            new_name='projector_availability',
        ),
    ]
